import Head from "next/head";
import { useRouter } from "next/router";
import { useFormContext } from "react-hook-form";
import { Formadora } from "../components";
import { Bitola } from "../components/Bitola";
import { Bitola as TBitola, Formadora as TFormadora } from "../graphql/graphql";
import { useFormadoras } from "../hooks";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const { data } = useFormadoras();
  const { watch, handleSubmit } = useFormContext();

  const formadoraId = watch("formadora");
  const bitolaId = watch("bitola");

  const onSubmit = () => router.push(`/passagens/${bitolaId}`);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Formadora data={data as TFormadora[]} />
        {formadoraId !== "-1" && (
          <Bitola
            data={data?.find((b) => b.id === formadoraId)?.bitolas as TBitola[]}
          />
        )}
        <input type="submit" disabled={Number(bitolaId) < 1} />
      </form>
      <p>Formadora: {watch("formadora")}</p>
      <p>Bitola: {watch("bitola")}</p>
    </div>
  );
}
