import Head from "next/head";
import { useFormContext } from "react-hook-form";
import { Formadora } from "../components";
import { Formadora as TFormadora } from "../graphql/graphql";
import { useFormadoras } from "../hooks";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data } = useFormadoras();
  const { watch, register, handleSubmit } = useFormContext();
  const formadoraId = watch("formadora");

  const onSubmit = (data: any) => console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Formadora data={data as TFormadora[]} />
        {formadoraId !== "-1" && (
          <select {...register("bitola")}>
            <option value="-1">Bitola</option>
            {data
              ?.find((f) => f.id === formadoraId)
              ?.bitolas.map((b) => (
                <option key={b.id} value={b.id}>
                  {b.tamanho.toFixed(2)} mm
                </option>
              ))}
          </select>
        )}
        <input type="submit" />
      </form>
      <p>Formadora: {watch("formadora")}</p>
      <p>Bitola: {watch("bitola")}</p>
    </div>
  );
}
